# Generated by Django 5.0.2 on 2024-03-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='body',
            field=models.TextField(default='updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twit',
            name='image_url',
            field=models.URLField(default='updated'),
            preserve_default=False,
        ),
    ]
