# Generated by Django 5.0.2 on 2024-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0002_twit_body_twit_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twit',
            options={'ordering': ['-updated']},
        ),
    ]
