# Generated by Django 5.0.2 on 2024-03-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0004_alter_twit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twit',
            options={'ordering': ['-updated']},
        ),
    ]
