# Generated by Django 5.0.2 on 2024-03-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
